---
title: "Introdução ao Git e ao Github"
author: "Marcelo Tonon"
date: "04/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

No mundo atual, é prática comum, é recomendada, que você tenha um backup na nuvem do seu projeto atual. Parece obvio, mas muita gente acaba sendo displicente em relação a manter um backup online do seu trabalho. Assim, a melhor forma de lidar com isso, é deixar o processo de backup o mais cômodo possível. E após alguma prática, o uso do Git/Github irá te proporcionar exatamente isso!

Além disso usar o Git ideal para quem mexe com códigos, uma vez que ele te permite realizar controles de alteração. Isso para projetos muito longos e/ou que você irá trabalhar em equipe. Foi pensando nisso que o Git foi concebido, por ninguém menos que Linus Torvalds, o criador do Linux!

O aproveitamento do Git é muito fortalecido quando usado com o Github, por se tratar do site mais popular e abrangente a oferecer o serviço Git. Assim, aqui irei usar as duas coisas juntas, porém há outras opções. Neste guia eu vou me basear muito no [capítulo escrito pelo Hadley Wickham](http://r-pkgs.had.co.nz/git.html).

# Instalando o Git!

Se você nunca usou e instalou o Git, a primeira coisa a fazer é instalar o Git no seu computador. Isso irá variar de sistema para sistema. Veja como fazer abaixo:


 - Windows: http://git-scm.com/download/win
 - OS X: http://git-scm.com/download/mac
 - Debian/Ubuntu: ```sudo apt-get install git-core```
 - Outras distros do Linux: http://git-scm.com/download/linux







# Git e Github

Aqui iremos

# Instalando o Git

# Comando Git via terminal

## Comandos Git para commit

- Para adicionar novos arquivos para a *"staging area"*.
```{bash, eval = FALSE}
git add -A
```

- Para dar commit em tudo que está na *"staging area"*

```{bash, eval = FALSE}
git commit -m "commiting all staging area"
```

- Para adicionar tudo à *"staging area"* e dar commit

```{bash, eval = FALSE}
git commit -a -m "including everything in the staging area and then commiting"
```

## Comandos git para dar push

 
```{bash, eval = FALSE}
git push <remote> <branch>
```

Para dar `push` via o terminal, você deve dizer qual é o destino `<remote>`, e qual ramificação `<branch>`, você deseja dar o push.

Assim, se você quer dar o push para origem na ramificação mestre (`master`), basta:

```{bash, eval = FALSE}
git push origin master
```

## Comandos para dar commit e push tudo junto

```{bash, eval = FALSE}
git commit -a -m "Mensagem do commit"

git push origin master
```


## Comandos git para renomear branchs

Suponha que você tem um ramo chamado `nome_velho`. Você 


